apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      n1:
        type: number
        default: 1
      s1:
        type: string
        default: hello world
      b1:
        type: boolean
        default: false
        required: true
      c1:
        type: choice
        options:
          - option1
          - option2
          - option3
        default: "option3"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo "n1 is '${{ inputs.n1}}'"
          echo "s1 is '${{ inputs.s1}}'"
          echo "b1 is '${{ inputs.b1}}'"
          echo "c1 is '${{ inputs.c1}}'"
