apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      b1:
        type: boolean
        default: false
        description: a boolean
      c1:
        type: choice
        options:
          - option1
          - option2
          - option3
        default: option1
        description: a choice
      n1:
        type: number
        required: true
        description: a number
      s1:
        type: string
        default: |
          hello world
          hello world
          hello world
          hello world
          hello world
        required: true
        description: a string
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "b1 is '${{ inputs.b1}}'"
          echo "c1 is '${{ inputs.c1}}'"
          echo "n1 is '${{ inputs.n1}}'"
          echo "s1 is '${{ inputs.s1}}'"
